theme: jekyll-theme-cayman
github:
  home_url: https://livian1107.github.io/CS5346/
  graduate_url: https://livian1107.github.io/CS5346/graduate.html
  vizsteps_url: https://livian1107.github.io/CS5346/vizsteps.html
  singapore_url: https://livian1107.github.io/CS5346/singapore_population/singapore.html
  export_url: https://livian1107.github.io/CS5346/export/export.html
  sars_url: https://livian1107.github.io/CS5346/sars/sars.html
